<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('monthly_reports', function (Blueprint $table) {
            $table->id();
            $table->year('year');
            $table->tinyInteger('month'); // 1-12
            
            // Statistics
            $table->integer('total_bookings')->default(0);
            $table->integer('confirmed_bookings')->default(0);
            $table->integer('cancelled_bookings')->default(0);
            $table->integer('completed_orders')->default(0);
            
            // Revenue
            $table->decimal('total_revenue', 15, 2)->default(0);
            $table->decimal('total_dp_collected', 15, 2)->default(0);
            $table->decimal('total_full_payment', 15, 2)->default(0);
            
            // Popular products
            $table->json('popular_products')->nullable(); // Top 5 products
            $table->json('popular_materials')->nullable(); // Top 5 materials
            
            // Generated by
            $table->foreignId('generated_by')->nullable()->constrained('users')->onDelete('set null');
            $table->dateTime('generated_at');
            
            $table->timestamps();
            
            // Unique constraint
            $table->unique(['year', 'month']);
        });
    }

    public function down()
    {
        Schema::dropIfExists('monthly_reports');
    }
};
